#define configMTIME_BASE_ADDRESS				0
#define configMTIMECMP_BASE_ADDRESS				0
#define configMINIMAL_STACK_SIZE				64
#define configMAX_PRIORITIES					2
#define configUSE_PREEMPTION					1
#define configUSE_IDLE_HOOK						0
#define configUSE_TICK_HOOK						0
#define configUSE_16_BIT_TICKS					0
#define configTOTAL_HEAP_SIZE					0x1000
#define configUSE_TASK_NOTIFICATIONS			0
#define configCPU_CLOCK_HZ						10000000
#define configTICK_RATE_HZ						100
#define configSUPPORT_STATIC_ALLOCATION			0
#define configSUPPORT_DYNAMIC_ALLOCATION		1
#define configUSE_TIMERS						0
#define INCLUDE_vTaskDelay						1
#define configAPPLICATION_ALLOCATED_HEAP		1
#define configCHECK_FOR_STACK_OVERFLOW			0
#define configNUM_CORES							1
#define configUSE_CORE_AFFINITY					0
